
[gsheets]
SPREADSHEET_ID = "1lLoWDMJ36X5cyd9Ysz5Lmkxc9WBZfwqSQQS2_EN9uHM"
WORKSHEET_NAME = "Textile Exchange Style Rules"
CAPS_WS_NAME   = "caps_whitelist"
READ_ONLY = true
ALLOW_CREATE = false

[google_service_account]
type = "service_account"
project_id = "streamlit-sheets-483818"
private_key_id = "6ad5b407f6b3c1202e9fcf738211e0ca3a3e5eb5"

private_key = """-----BEGIN PRIVATE KEY-----
MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCkfJ4Kx8JnfNaI
2L9OKwYemo+CX2QFZuiVnRmaw1sFz+G44ln5qMbhrFmDBeTjZczPgeJFk/+7Qy+B
i+OjVThdMh5cmzL0KvWqnja2l11upYEDuSZYElSjTVpp7HQzPnMxnnXyMrfxl3Vi
wNCTtYjUkWGPLnuLeBv+YNG56Acz2FYWSvkY56T90eGEJPRDI4tfls2ka7+Ie5i+
QCg/JvIjbSFqs3Nxw2zVJwJhP6tnhVhW8rotwpTv4rHqrOEIvxLRF1UFCFMDCRNT
JfjoqZfmnAS59mXxoybdeo8W5RKkrJnUEtJfN5zf1Xmuuu0F6zuKvQKgwwq8v8Xi
YyL+nMqdAgMBAAECggEAAmG/lB5iZUc8gAzLcGFVHFpWm6ev9hgQZCI7Pa94gPQK
q7ezX9ce0iPBxBDwyI4v0g1qbmF/QYHujSyuZi4Uu9y+7c5dhYWduxPBbRFyC+kf
niMvN/VD/n1fQstmv1s3Jc/Km3A6k6gCziRGoOzvB0z3obAln9ZkaWGTh+KhQBHq
6mCVVhm2wXAq8395crFRkrj8x3e8DdApEdovoaDapoU6N7CPhMbu3CsXlzwWF+EG
vhiERhS+IJDw0JxJV7lPOzxx4eS9l9AfSXMgIICf8JKHhtBKbPnysIr4P2Hxv203
Efr5J0KvwfpgReg79UkLYo+8LPe24nYJluKa17QajQKBgQDlXrGUktVfv63Hpl43
5dSuTPH2Z75/OkuG0rARWr0veqs6G7ns7YN/FOziNnk5mT62u2mfHwEHVN76l5Eb
wOqvgSewDgP7FdNu3rSFvNIeEy0Y+M/hxwI8gLX07ricOZf3nFcSEosjimkj84+m
VuULaPTIUsLa5T6iRfTcSzQaWwKBgQC3lXmjdmlw5wer5Tb4NKM527tddBu2CrDG
p4PR4mTUXLf+QqAt8etSnObV5UPLGtrUjw6JOi6/sncR0IS4D0Y83AcU0rON/6E/
rlRuJW8661CubU4bKKO0AjinjL3Tp4Qt5kE+wLZzOEDWDzJTfe11kOPQXsFfiqUA
1UwXI+mQZwKBgHuMXzD9SovRrqSc+6E2XjIo5ihox1a2qtoLgKVIcCEz/SlGqAZ0
BWGdft92oiOhZQN+vazlQWOWlqj6nUIKzx8L/bm6QvCrWAEfWrOy+qcSgzcxRqCB
1rWKSviM4cncx/urLcdhT6ssMegYmKbrpWJY/Ykt8yF/XBaCghtrMryDAoGAVGo4
B3DwZQjmnyUD1LengnhGPF+iSl+6D26Bj6XxRTDpLdIHA3llApTBFAOa266ahvjM
707Apkbyt09RZ60mV9+4pduI0reDttt7WTZ/YfFIJRx/uL9EHwaSdICj3Mn/Xnes
8qT8gBiSv5s3Qer6oH+iMXMQqdT/sFVj6pQJ1usCgYAIqp1asbycc7bZvJJUnZHS
CfAGBU0wmR+vgBImYuV1+s+Le8sLfbdK9HqH4EN8X1p4Yvs+QGNy1IJhw5ppaNPs
2QTS6a9hfH2+2MXE6REEMIQdb7msq0FQyjBAPV/GqEghRcBobE5G05c25G1KGsL7
OCEVb5ryt+5becU/mnGKmw==
-----END PRIVATE KEY-----
"""

client_email = "stream-lit-take-two@streamlit-sheets-483818.iam.gserviceaccount.com"
client_id = "112797505422876509851"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
